### ISSUE TITLE
MassAction block is not available on all course formats (only on topics or weeks)

### ISSUE THREAD

**Issue by nadavkav** [hqhoang/moodle-block_massaction#4]
Hello,

Is there any reason the block can not work on other (any) course formats?

```function applicable_formats() {
        return array('course-view-weeks' => true, 'course-view-topics' => true);
    }

```
I need it to work on a new course format I made (moonstone) and on a 3rd party course format: "topcoll".

```

**Comment by hqhoang** [comment]
hey,

I'm not sure, I inherited this project at work. The block puts 
checkboxes next to each activity/resource, and the action will be 
applied to the checked items. The checkboxes are added dynamically 
in-browser (Javascript) by parsing the DOM for certain elements (relying 
on the consistency of the layout).

If your format consistently lists out the activities and resources in a 
parse-able manner (e.g. having CSS classes to help searching for them on 
the DOM), then I think it's fairly straightforward to add support for 
your format.

Do you have sample/screenshot of your format?

--huy

On 07/29/2013 11:09 AM, Nadav Kavalerchik wrote:

> Hello,
> 
> Is there any reason the block can not work on other (any) course formats?
> 
> ```function applicable_formats() {
> return array('course-view-weeks' => true, 'course-view-topics' => true);
> }
> 
> |I need it to work on a new course format I made (moonstone) and on a 3rd party course format: "topcoll".
> 
> |
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/hqhoang/moodle-block_massaction/issues/4.

## 

it's not the software that's free; it's you

http://en.wikipedia.org/wiki/Free_software
http://www.gnu.org/philosophy/schools.html

**Comment by nadavkav** [comment]
I am using a variation to "topcoll" course format.

I have already removed the restriction in the block and it works fine.

I guess you can not tell what kind of future course format will be
developed, so you might consider removing this restriction.
And hope that course format that breaks the layout which will prevent users
from using this block with not use those formats.

Initially enabling only "topics" and "weeks" and adding each new course
format in the future to the list each time seems problematic.
What do you think?

**Comment by hqhoang** [comment]
I guess I'm from a different situation/perspective. I'm part of a team 
that provides support for Moodle at UMN, with 50K+ enrollments each 
semester. Instead of letting users try out something doesn't work and 
flood the service desk, it's probably better to prevent 
problem/confusion for users in the first place. Of course, if we have 
request from users  to support other formats  (like you did), we would 
then modify the code and test it thoroughly before opening it to users 
(it's just part of QA).

Another factor probably is training. We discuss and get feedbacks from 
our users, develop "best practices", and incorporate those into our 
training. Thus, it's rare to have someone straying out of the usual work 
flow.

So, I'm still leaning toward keeping the format list inclusive. As an 
analogy, it's better to prevent users from plugging a USB cable into an 
HDMI jack by designing the sockets differently, instead of having them 
scratching their heads wondering why the TV doesn't get any signal from 
the DVD player.

If your format is standard in Moodle, or can be downloaded publicly and 
used as is, we certainly should add it to the supported formats after 
testing. Otherwise, it might be bad if somebody else has another 
variation of the same format that doesn't work with the block.

**Comment by nadavkav** [comment]
Thank you for your detailed response.
I understand you perfectly. We have similar issues :-(

I will make a local fix, since this course format is not released publicly, yet.
Again, Thank you very much!
